
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../../providers/Providers";
import { ReactNode } from "react";
import { Cairo } from "next/font/google";
import Header from "@/components/header/Header";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "اكاديمية سرج للدرسات والابحاث الفكرية المعاصرة - sorooj academy for contemporary intellectual studies and research",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <html lang={lang} dir={dir} className={cairo.variable}>
      <body className="overflow-x-hidden">
        <Providers>
        <div className="">

              <div>

                <header className="absolute top-0 left-0 w-full z-50 bg-transparent">
                    <Header />
                </header>

                <main className="">
                  <div className="mx-auto">
                    {children}
                  </div>
                </main>

                {/* <footer> copy right footer</footer> */}

              </div>

        </div>
        </Providers>
      </body>
    </html>
  );
}